name: ci

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            accept-flake-config = true
      - run: nix flake check
      - run: nix build .#env .#desktop
      - run: nix fmt -- --check .
